server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring:
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/doctor?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: eh@sjgy
    driverClassName: com.mysql.jdbc.Driver
  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/static/flowable-modeler
  redis:
    open: true       # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: localhost
    port: 6379
    password:         # 密码（默认为空）
    timeout: 6000ms   # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
flowable:
  #关闭定时任务JOB
  async-executor-activate: false